Associations
rega1237/OOP-school-library pull request #3
Opened 2022-07-20 21:54 UTC by rega1237

# Build in this branch
- Create Classroom class
- Make the relationship between classroom and student
- Create Rental class 
- Create Book class
- Make the many to many relationship between rental, book and person (and sub classes)

2022-07-20 22:42 UTC, codepantha requested changes
# STATUS: REQUIRED CHANGES ♻️ 

## Hi @rega1237 👋, 

Good job so far 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/UsOoz5EYqRxXW/giphy.gif"/>

### Highlights ⭐ 
✔️ Descriptive PR
✔️ Good GitFlow
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please add a method for adding rentals in the Person class. This is important in order to establish a has-many and a belongs-to relationship between Person and Rental

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 22:42 UTC, codepantha commented on rental.rb
> +  attr_accessor :date
- [ ] You have specified getters for person and book. Please specify setters as well since it's a project requirement 👍

2022-07-20 22:42 UTC, codepantha commented on book.rb
> +end
- [ ] Please add a method for adding rentals in the Book class. This is important in order to establish relationship between `Person` and `Book` using the intermediate class `Rental`

2022-07-21 00:48 UTC, uwadonat approved these changes
## Hi @rega1237, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
### Highlights
- Descriptive pull request message with title ✔️
- Professional  readme file ✔️
![approval](https://user-images.githubusercontent.com/65860678/180106345-cfa51a3f-4f52-402c-b53d-f1673a144f05.gif)


# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-21 01:41 UTC, merged